name: backup-validator

on:
  push:
    branches: [ master ]
    paths:
    - 'github-backup/**'
    - .github/workflows/backup-validator.yaml

env:
  IMAGE_NAME: backup-validator

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" ${IMAGE_NAME}/

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo "pushing ${IMAGE_NAME}"
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker push $IMAGE_ID:latest
