name: dotnet7x

on:
  push:
    branches: [ master ]
    paths:
    - 'dotnet7x/**'
    - .github/workflows/dotnet7x.yaml

env:
  IMAGE_NAME: dotnet7x

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for master branch

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        BASE_VERSION=$(cat ${IMAGE_NAME}/version)
        docker build --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --build-arg BASE_VERSION=${BASE_VERSION} ${IMAGE_NAME}/

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        BASE_VERSION=$(cat ${IMAGE_NAME}/version)
        echo "pushing ${IMAGE_NAME} version ${BASE_VERSION}"
        docker tag $IMAGE_NAME $IMAGE_ID:latest
        docker tag $IMAGE_NAME $IMAGE_ID:${BASE_VERSION}
        docker push $IMAGE_ID:latest
        docker push $IMAGE_ID:${BASE_VERSION}
